[project]
name = "analysis"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.8.2",
    "pygobject>=3.50.0",
    "scipy>=1.14.1",
    "seaborn>=0.13.2",
]

[tool.ruff]
line-length = 89
