[data]
files_prefix = "data/2025/03/"
files = [
    "18/zantiks_a/light_dark_transition-20250318T113547.csv",
    "18/zantiks_b/light_dark_transition-20250318T114015.csv",
    "18/zantiks_a/startle_response-20250318T124450.csv",
    "18/zantiks_b/startle_response-20250318T124645.csv",
    "18/light_dark_preference/a/light_dark_preference-20250318T153140.csv",
    "18/light_dark_preference/b/light_dark_preference-20250318T135636.csv",
    "18/ymaze_15/a/ymaze_15-20250318T135312.csv",
    "18/ymaze_15/b/ymaze_15-20250318T153126.csv"
]
assay_names = [
    "light/dark transition",
    "light/dark transition",
    "startle response/pre-pulse inhibition",
    "startle response/pre-pulse inhibition",
    "light/dark preference",
    "light/dark preference",
    "y-maze 15",
    "y-maze 15"
]

[genotypes]
files_prefix = "data/2025/03/18/genotypes.csv"
files = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
]
counting_directions = [
    "down",
    "down",
    "down",
    "down",
    "across",
    "across",
    "across",
    "across",
]

[fish_used]
files_prefix = "templates/fish_used/"
files = [
    "zantiks_left.txt",
    "zantiks_right.txt",
    "zantiks_left.txt",
    "zantiks_right.txt",
    "twelve_1.txt",
    "twelve_2.txt",
    "twelve_1.txt",
    "twelve_2.txt"
]

[output]
file = ""
