[data]
files_prefix = "2024/12/18/ymaze_4/"
files = [
    "a/ymaze_4-20241218T093343.csv",
    "b/ymaze_4-20241218T105433.csv",
    "c/ymaze_4-20241218T122606.csv",
    "d/ymaze_4-20241218T134518.csv"
]
assay_names = [
    "y-maze 4",
    "y-maze 4",
    "y-maze 4",
    "y-maze 4"
]

[genotypes]
files_prefix = "2024/12/18/genotypes.csv"
files = [
    "",
    "",
    "",
    ""
]
counting_directions = [
    "across",
    "across",
    "across",
    "across",
]

[fish_used]
files_prefix = "2024/12/18/ymaze_4/"
files = [
    "a/fish_used.txt",
    "b/fish_used.txt",
    "c/fish_used.txt",
    "d/fish_used.txt"
]
