[data]
files_prefix = ""
files = [
    "2024/12/06/mirror_biting/a/mirror_biting-20241206T110125.csv",
    "2024/12/06/mirror_biting/b/mirror_biting-20241206T121849.csv",
    "2024/12/18/mirror_biting/ab/mirror_biting-20241218T122632.csv",
    "2024/12/18/mirror_biting/cd/mirror_biting-20241218T093359.csv",
    "2025/02/04/mirror_biting/abd/mirror_biting-20250204T123554.csv",
    "2025/02/04/mirror_biting/c/mirror_biting-20250204T095111.csv",
    "2025/02/06/mirror_biting/ab/mirror_biting-20250206T123258.csv",
    "2025/02/06/mirror_biting/cd/mirror_biting-20250206T095505.csv"
]
assay_names = [
    "mirror biting",
    "mirror biting",
    "mirror biting",
    "mirror biting",
    "mirror biting",
    "mirror biting",
    "mirror biting",
    "mirror biting"
]

[genotypes]
files_prefix = ""
files = ["2024/12/06/genotypes.csv", "2024/12/06/genotypes.csv", "2024/12/18/genotypes.csv", "2024/12/18/genotypes.csv", "2025/02/04/genotypes.csv", "2025/02/04/genotypes.csv", "2025/02/06/genotypes.csv", "2025/02/06/genotypes.csv"]
counting_directions = ["across", "across", "across", "across", "across", "across", "across", "across"]

[fish_used]
files_prefix = ""
files = [
    "2024/12/06/mirror_biting/a/fish_used.txt",
    "2024/12/06/mirror_biting/b/fish_used.txt",
    "templates/fish_used/eight_1.txt",
    "templates/fish_used/eight_2.txt",
    "2025/02/04/eight_1.txt",
    "2025/02/04/eight_2.txt",
    "templates/fish_used/eight_1.txt",
    "templates/fish_used/eight_2.txt"
]
