[data]
files_prefix = "2024/12/09/light_dark_preference/"
files = [
    "a/light_dark_preference-20241209T121344.csv",
    "b/light_dark_preference-20241209T130731.csv",
    "c/light_dark_preference-20241209T142400.csv"
]
assay_names = ["light/dark preference", "light/dark preference", "light/dark preference"]

[genotypes]
files_prefix = "2024/12/09/genotypes.csv"
files = ["", "", ""]
counting_directions = ["across", "across", "across"]

[fish_used]
files_prefix = "2024/12/09/light_dark_preference/"
files = ["a/fish_used.txt", "b/fish_used.txt", "c/fish_used.txt"]
