[data]
files_prefix = "data/"
files = [
    "2024/12/09/light_dark_preference/a/light_dark_preference-20241209T121344.csv",
    "2024/12/09/light_dark_preference/b/light_dark_preference-20241209T130731.csv",
    "2024/12/09/light_dark_preference/c/light_dark_preference-20241209T142400.csv",
    "2025/01/13/light_dark_preference/a/light_dark_preference-20250113T121403.csv",
    "2025/01/13/light_dark_preference/b/light_dark_preference-20250113T125912.csv",
    "2025/01/13/light_dark_preference/c/light_dark_preference-20250113T134009.csv",
]
assay_names = ["light/dark preference", "light/dark preference", "light/dark preference", "light/dark preference", "light/dark preference", "light/dark preference"]

[genotypes]
files_prefix = "data/"
files = ["2024/12/09/genotypes.csv", "2024/12/09/genotypes.csv", "2024/12/09/genotypes.csv", "2025/01/13/genotypes.csv", "2025/01/13/genotypes.csv", "2025/01/13/genotypes.csv"]
counting_directions = ["across", "across", "across", "across", "across", "across"]

[fish_used]
files_prefix = "templates/fish_used/twelve_"
files = ["2.txt", "3.txt", "1.txt", "1.txt", "2.txt", "3.txt"]
