[data]
files_prefix = "2024/12/09/zantiks_"
files = ["a/startle_response-20241209T105820.csv", "b/startle_response-20241209T105839.csv"]
assay_names = ["startle response/pre-pulse inhibition", "startle response/pre-pulse inhibition"]

[genotypes]
files_prefix = "2024/12/09/genotypes.csv"
files = ["", ""]
counting_directions = ["down", "down"]

[fish_used]
files_prefix = "2024/12/09/zantiks_"
files = ["a/fish_used.txt", "b/fish_used.txt"]
