[data]
files_prefix = "data/2024/"
files = [
    "11/01/ymaze_15/a/ymaze_15-20241101T164208.csv",
    "11/01/ymaze_15/b/ymaze_15-20241101T175733.csv",
    "11/01/ymaze_15/c/ymaze_15-20241101T191455.csv",
    "11/01/ymaze_15/d/ymaze_15-20241101T202944.csv",
    "11/04/ymaze_15/a/ymaze_15-20241104T170903.csv",
    "11/04/ymaze_15/b/ymaze_15-20241104T182427.csv",
    "11/04/ymaze_15/c/ymaze_15-20241104T194506.csv",
    "12/09/ymaze_15/a/ymaze_15-20241209T121317.csv",
    "12/09/ymaze_15/b/ymaze_15-20241209T130440.csv",
    "12/09/ymaze_15/c/ymaze_15-20241209T142016.csv"
]
assay_names = [
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15"
]

[genotypes]
files_prefix = "data/2024/"
files = [
    "11/01/genotypes.csv",
    "11/01/genotypes.csv",
    "11/01/genotypes.csv",
    "11/01/genotypes.csv",
    "11/04/genotypes.csv",
    "11/04/genotypes.csv",
    "11/04/genotypes.csv",
    "12/09/genotypes.csv",
    "12/09/genotypes.csv",
    "12/09/genotypes.csv"
]
counting_directions = [
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
    "across"
]

[fish_used]
files_prefix = "data/2024/"
files = [
    "11/01/ymaze_15/a/fish_used.txt",
    "11/01/ymaze_15/b/fish_used.txt",
    "11/01/ymaze_15/c/fish_used.txt",
    "11/01/ymaze_15/d/fish_used.txt",
    "11/04/ymaze_15/a/fish_used.txt",
    "11/04/ymaze_15/b/fish_used.txt",
    "11/04/ymaze_15/c/fish_used.txt",
    "12/09/ymaze_15/a/fish_used.txt",
    "12/09/ymaze_15/b/fish_used.txt",
    "12/09/ymaze_15/c/fish_used.txt"
]
