[data]
files_prefix = "data/"
files = [
    "2024/12/09/zantiks_a/light_dark_transition-20241209T093738.csv",
    "2024/12/09/zantiks_b/light_dark_transition-20241209T093756.csv",
    "2025/01/13/zantiks_a/light_dark_transition-20250113T095238.csv",
    "2025/03/20/zantiks_a/light_dark_transition-20250320T092135.csv",
    "2025/03/20/zantiks_b/light_dark_transition-20250320T092152.csv",
    "2025/03/18/zantiks_a/light_dark_transition-20250318T113547.csv",
    "2025/03/18/zantiks_b/light_dark_transition-20250318T114015.csv",
    "2025/04/02/zantiks_a/light_dark_transition-20250402T075743.csv",
    "2025/04/02/zantiks_b/light_dark_transition-20250402T075758.csv",
]
assay_names = [
    "light/dark transition",
    "light/dark transition",
    "light/dark transition",
    "light/dark transition",
    "light/dark transition",
    "light/dark transition",
    "light/dark transition",
    "light/dark transition",
    "light/dark transition",
]

[genotypes]
files_prefix = "data/"
files = [
    "2024/12/09/genotypes.csv",
    "2024/12/09/genotypes.csv",
    "2025/01/13/genotypes.csv",
    "2025/03/20/genotypes.csv",
    "2025/03/20/genotypes.csv",
    "2025/03/18/genotypes.csv",
    "2025/03/18/genotypes.csv",
    "2025/04/02/genotypes.csv",
    "2025/04/02/genotypes.csv",
]
counting_directions = [
    "down",
    "down",
    "down",
    "down",
    "down",
    "down",
    "down",
    "down",
    "down",
]

[fish_used]
files_prefix = "templates/fish_used/zantiks_"
files = [
    "left.txt",
    "right.txt",
    "left.txt",
    "left.txt",
    "right.txt",
    "left.txt",
    "right.txt",
    "left.txt",
    "right.txt",
]

[output]
file = ""
