[data]
files_prefix = "data/"
files = [
    "2025/05/05/sleep/a/sleep-20250505T075445.csv",
    "2025/05/05/sleep/b/sleep-20250505T075459.csv",
    "2025/06/11/sleep/a/sleep-20250603T075441.csv",
    "2025/04/02/zantiks_a/sleep-20250401T075448.csv",
    "2025/04/02/zantiks_b/sleep-20250401T075504.csv",
]
assay_names = [
    "sleep",
    "sleep",
    "sleep",
    "sleep",
    "sleep",
]

[genotypes]
files_prefix = "data/"
files = [
    "2025/05/05/genotypes.csv",
    "2025/05/05/genotypes.csv",
    "2025/06/11/genotypes.csv",
    "2025/04/02/genotypes.csv",
    "2025/04/02/genotypes.csv",
]
counting_directions = [
    "down",
    "down",
    "down",
    "down",
    "down",
]

[fish_used]
files_prefix = "templates/fish_used/zantiks_"
files = [
    "left.txt",
    "right.txt",
    "left.txt",
    "left.txt",
    "right.txt",
]

[output]
file = ""
