[data]
files_prefix = "data/"
files = [
    "2024/11/01/ymaze_15/a/ymaze_15-20241101T164208.csv",
    "2024/11/01/ymaze_15/b/ymaze_15-20241101T175733.csv",
    "2024/11/01/ymaze_15/c/ymaze_15-20241101T191455.csv",
    "2024/11/01/ymaze_15/d/ymaze_15-20241101T202944.csv",
    "2024/11/04/ymaze_15/a/ymaze_15-20241104T170903.csv",
    "2024/11/04/ymaze_15/b/ymaze_15-20241104T182427.csv",
    "2024/11/04/ymaze_15/c/ymaze_15-20241104T194506.csv",
    "2024/12/09/ymaze_15/a/ymaze_15-20241209T121317.csv",
    "2024/12/09/ymaze_15/b/ymaze_15-20241209T130440.csv",
    "2024/12/09/ymaze_15/c/ymaze_15-20241209T142016.csv",
    "2025/03/20/ymaze_15/a/ymaze_15-20250320T115852.csv",
    "2025/03/20/ymaze_15/b/ymaze_15-20250320T132625.csv",
    "2025/04/15/ymaze_15/a/ymaze_15-20250415T110436.csv",
    "2025/04/15/ymaze_15/b/ymaze_15-20250415T121831.csv",
    "2025/04/15/ymaze_15/c/ymaze_15-20250415T141244.csv",
    "2025/03/18/ymaze_15/a/ymaze_15-20250318T135312.csv",
    "2025/03/18/ymaze_15/b/ymaze_15-20250318T153126.csv",
    "2025/04/02/ymaze_15/a/ymaze_15-20250402T114001.csv",
    "2025/04/02/ymaze_15/b/ymaze_15-20250402T134141.csv",
    "2025/04/02/ymaze_15/c/ymaze_15-20250402T144930.csv",
]
assay_names = [
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
    "y-maze 15",
]

[genotypes]
files_prefix = "data/"
files = [
    "2024/11/01/genotypes.csv",
    "2024/11/01/genotypes.csv",
    "2024/11/01/genotypes.csv",
    "2024/11/01/genotypes.csv",
    "2024/11/04/genotypes.csv",
    "2024/11/04/genotypes.csv",
    "2024/11/04/genotypes.csv",
    "2024/12/09/genotypes.csv",
    "2024/12/09/genotypes.csv",
    "2024/12/09/genotypes.csv",
    "2025/03/20/genotypes.csv",
    "2025/03/20/genotypes.csv",
    "2025/04/15/genotypes.csv",
    "2025/04/15/genotypes.csv",
    "2025/04/15/genotypes.csv",
    "2025/03/18/genotypes.csv",
    "2025/03/18/genotypes.csv",
    "2025/04/02/genotypes.csv",
    "2025/04/02/genotypes.csv",
    "2025/04/02/genotypes.csv",
]
counting_directions = [
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
    "across",
]

[fish_used]
files_prefix = ""
files = [
    "data/2024/11/01/ymaze_15/a/fish_used.txt",
    "data/2024/11/01/ymaze_15/b/fish_used.txt",
    "data/2024/11/01/ymaze_15/c/fish_used.txt",
    "data/2024/11/01/ymaze_15/d/fish_used.txt",
    "data/2024/11/04/ymaze_15/a/fish_used.txt",
    "data/2024/11/04/ymaze_15/b/fish_used.txt",
    "data/2024/11/04/ymaze_15/c/fish_used.txt",
    "data/2024/12/09/ymaze_15/a/fish_used.txt",
    "data/2024/12/09/ymaze_15/b/fish_used.txt",
    "data/2024/12/09/ymaze_15/c/fish_used.txt",
    "templates/fish_used/twelve_1.txt",
    "templates/fish_used/twelve_2.txt",
    "templates/fish_used/twelve_1.txt",
    "templates/fish_used/twelve_2.txt",
    "templates/fish_used/twelve_3.txt",
    "templates/fish_used/twelve_1.txt",
    "templates/fish_used/twelve_2.txt",
    "templates/fish_used/twelve_1.txt",
    "templates/fish_used/twelve_2.txt",
    "templates/fish_used/twelve_3.txt",
]

[output]
file = ""
